FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends gcc && \
    rm -rf /var/lib/apt/lists/*

COPY pyproject.toml .
RUN pip install -e ".[dev]" && pip cache purge

COPY . .

CMD ["uvicorn", "xillion.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
